-- Create the narrative_entries table if it doesn't exist
CREATE TABLE IF NOT EXISTS `narrative_entries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `campus` varchar(100) NOT NULL,
  `year` varchar(10) NOT NULL,
  `title` varchar(255) NOT NULL,
  `background` text NOT NULL,
  `participants` text NOT NULL,
  `topics` text NOT NULL,
  `results` text NOT NULL,
  `lessons` text NOT NULL,
  `what_worked` text NOT NULL,
  `issues` text NOT NULL,
  `recommendations` text NOT NULL,
  `ps_attribution` varchar(255) DEFAULT NULL,
  `evaluation` text NOT NULL,
  `photo_path` text DEFAULT NULL,
  `photo_caption` text DEFAULT NULL,
  `gender_issue` varchar(255) DEFAULT NULL,
  `created_by` varchar(100) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci; 